### ISSUE TITLE
Share button gives floating point number for daily Survivle 

### ISSUE THREAD

**Issue by jamesbisraelson-old** [lazyguyy/survivle#10]
When I hit the share button I get:

Daily Survivle 8.958333333333334: 7 rounds
⬛⬛🟨⬛⬛
⬛🟨⬛⬛⬛
🟨⬛⬛⬛⬛
⬛🟨⬛🟩⬛
⬛⬛🟩🟩🟨
🟨⬛🟩🟩🟩
🟩🟩🟩🟩🟩
https://lazyguyy.github.io/survivle/

It should say Daily Survivle 9: 7 rounds... etc.

p.s. love this version of the game. great idea for a wordle spinoff

**Comment by lazyguyy** [comment]
Uh huh that's odd. Which browser / system configuration are you running?

**Comment by jamesbisraelson-old** [comment]
This is on Android 12, Pixel 6, Google Chrome 99.0.4844.58.

**Comment by lazyguyy** [comment]
Hmm that's weird, I'm running the same operating system with the very same chrome version, and it didn't produce this floating point mess for me. However, I slightly altered the logic so it should work now anyways.
If the problem persists, feel free to reopen the issue and I'll look into it further.
