### ISSUE TITLE
Solution changes, but my guesses remain in place

### ISSUE THREAD

**Issue by eakarink** [lazyguyy/survivle#12]
When I'm up past midnight I do the new Survivle, but for the past few days, when I revisit the site during the day, the solution has changed but all of my previous guesses are still in place. For example, when I did the puzzle at 12:30am or whatever last night, the solution was OUTGO. When I reloaded this morning, it was FILLY. You can see in the attached screenshot that all of my previous guesses from OUTGO are still loaded.
I'm on an Android phone using Firefox, and I'm in the Central time zone in case that somehow winds up mattering.
![Screenshot_20220317-131507_Firefox](https://user-images.githubusercontent.com/101830657/158879174-b3d92649-d265-41c4-9aee-6701c0929c9d.jpg)

**Comment by lazyguyy** [comment]
Oh I see how that happens. Will fix it as soon as I get time. Thanks for reporting

**Comment by lazyguyy** [comment]
Might be fixed, at least I added some code to address what I think the issue was. If the problem persists, feel free to reopen the issue!
