### ISSUE TITLE
"hard mode" rules not consistently applied

### ISSUE THREAD

**Issue by kroll-101** [lazyguyy/survivle#13]
![Screenshot_20220328-232924](https://user-images.githubusercontent.com/60220648/160498053-67dde0c9-033a-41b0-9628-8d8c9c88b79e.png)

1. Guess a word that results in one yellow square.
2. Guess another word where the position that was yellow is replaced by a green letter.

Expectation:
Game should prompt you to try and place the yellow letter elsewhere in the word.

Instead:
Game forgets the yellow letter if that space is now green.

See what happens to the letter O in the screenshot attached 

Suspect an issue in the order of logic followed in enforcing hard mode.

**Comment by lazyguyy** [comment]
I cannot reproduce this bug, the system recognizes that I didnt use all information: (secret word is PRANK)

TUMOR
CHICK <- The word must contain the letter R at least once.

Also, even more egregious is the fact that you were able to enter a word that didn't contain an S when it was revelaed with the yellow square in PILLS that an S is part of the target word. Could you try to reproduce it again (start a random survivle, reveal the target word and then do exactly what you described in your post)?

**Comment by kroll-101** [comment]
Frustratingly, can't reproduce now despite multiple attempts.

The puzzle was completed at 23:29 (+01:00 GMT) yesterday. Could it be some weird effect as the word changes over? (I'll reattempt tonight at a similar time).

**Comment by lazyguyy** [comment]
Yes, I assume it must be something like that. However, the cache should get cleared when the new day starts and you reload the page or start a new survivle. Only thing I could imagine is if you run Survivle in multiple tabs and switch between them and then some weird cache things happen, but that seems rather improbable.
Please keep me posted if you manage to recreate the bug

**Comment by lazyguyy** [comment]
I assume the issue hasn't popped up again. Should you manage to recreate it, please feel free to reopen the issue. Thanks!

**Comment by kroll-101** [comment]
Yes, despite a few attempts, haven't seen it since. Thanks for looking into it.
