### ISSUE TITLE
Help text doesn’t say what’s a “winning” score

### ISSUE THREAD

**Issue by swar00p** [lazyguyy/survivle#14]
When I was “forced” to guess the correct word on my 6th attempt, I saw a message at the top that said something like I almost won. It would be good to know what that “winning” score is. Is it 6 attempts or 7?

**Comment by lazyguyy** [comment]
Well I would define winning Survivle as taking seven or more guesses, since the goal is to lose in Wordle, i.e. take more than six guesses. I have added a paragraph in the help section.
Thanks for playing!
