### ISSUE TITLE
Can't close info

### ISSUE THREAD

**Issue by boephe** [lazyguyy/survivle#15]
When I press the little i in the top-left on my Android in Edge it pops up the explanation but I can't see an x or close button. If I refresh the page it goes back to the game page.

**Comment by lazyguyy** [comment]
The info panel should close no matter where you press on the screen (thats why there is no x button). If that doesn't work, would you please share you browser version?

**Comment by boephe** [comment]
Sorry, you're right. Not thinking clearly at 11:30pm

**Comment by lazyguyy** [comment]
Haha, no worries. Happens to the best of us. Thanks for playing!
