### ISSUE TITLE
Zooming doesn't work

### ISSUE THREAD

**Issue by dllu** [lazyguyy/survivle#17]
Sometimes I have an awe-inspiring performance but I can't zoom out to screenshot the whole thing.

See also: [Please stop disabling zoom](https://www.matuzo.at/blog/2022/please-stop-disabling-zoom/).

![image](https://user-images.githubusercontent.com/14482624/168378976-2381f1c7-1e91-486c-be6a-6e3d4080df44.png)

As you can see below the size is almost the same even at 33%. 
![image](https://user-images.githubusercontent.com/14482624/168379023-6d92dcbf-da23-4773-975d-40a22ff8ea21.png)

**Comment by lazyguyy** [comment]
I'm not sure why exactly I put this there. I think it was to prevent double tap zooming on safari, but according to the article safari ignores that anyway?
Regardless, I'm not sure that would change much, as I (naively perhaps, I still don't know) wrote all the UI stuff with viewport units which kind of make zooming impossible, if my understanding is correct. But anyway, I edited the offending line. I hope it wokrs now.

**Comment by dllu** [comment]
hmm yeah viewport units are probably to blame...

**Comment by lazyguyy** [comment]
It's been a minute, but I finally rewrote the interface and got rid of viewport units for styling the game board. Zooming should work now, so I'm closing this and a related issue. Please reopen if it's still not working.
