### ISSUE TITLE
Not an issue but a request?

### ISSUE THREAD

**Issue by ashtea96** [lazyguyy/survivle#2]
I would love if there were a way to share your results like with actual wordle (and the several spin-offs). Sorry for submitting this as an issue, i didn't know how else to request this

**Comment by lazyguyy** [comment]
You are absolutely in luck: I was working on this feature right as you opened this issue and have already deployed it.
Enjoy! and thank you for the feedback.

**Comment by ashtea96** [comment]
Yay!! Tyty 😊
