### ISSUE TITLE
Android : Sharing result to Twitter doesn't show puzzle number

### ISSUE THREAD

**Issue by win7guru** [lazyguyy/survivle#5]
Just tried out the share option after completing a second puzzle (after tapping the reload icon) and when sharing it to Twitter, only the guesses were shown and not the puzzle number. 

This occurs on Google Chrome on Android 10

![Screenshot_20220307-232851](https://user-images.githubusercontent.com/650640/157172475-d0cd4853-159e-4e82-a884-a36df4e133c1.png)

**Comment by lazyguyy** [comment]
I see. I wanted to show the difference between the daily survivle and a random one, but I think I will do that differently.

**Comment by lazyguyy** [comment]
Alright, I fixed that.

**Comment by win7guru** [comment]
Thank you for fixing it.
