### ISSUE TITLE
Can't use E in place I haven't used it yet

### ISSUE THREAD

**Issue by coopa2134** [lazyguyy/survivle#6]
It says that e can't be used in the fourth place even though I haven't used it there yet, and I haven't made it green yet. Not sure if pries just isn't in the word list and it's misidentifying the problem though.
![Screenshot_20220308-040954](https://user-images.githubusercontent.com/101177181/157205953-7f8efa4b-78f4-4963-a917-078ae8d1a77e.png)

**Comment by coopa2134** [comment]
Update: pries is in word list. Not sure if I'm missing something because I'm tired but seems like I should be able to use E there

**Comment by lazyguyy** [comment]
But doesn't creep have an "e" as its fourth letter? It was marked gray and therefore we know for subsequent guesses that there cannot be an "e". It appears to me it is working as intended, or am I missing something? Feel free to repoen the issue if that is the case.

**Comment by coopa2134** [comment]
Yup, no, that's my bad. As I said, I was tired haha. Sorry about that
