### ISSUE TITLE
No submit button

### ISSUE THREAD

**Issue by Lulu1295** [lazyguyy/survivle#7]
Using Chrome on Samsung s22 ultra, no submit button

**Comment by lazyguyy** [comment]
Can you share a screenshot?

**Comment by Lulu1295** [comment]
![Screenshot_20220308-151801_Chrome](https://user-images.githubusercontent.com/101196164/157267868-b31d0b4c-5863-44f2-b29c-8cec7f4cb5d9.jpg)

**Comment by lazyguyy** [comment]
The submit button is below the a-button and right next to the z-button
