### ISSUE TITLE
seeing parts of multiple games from today when returning 

### ISSUE THREAD

**Issue by PaulCzege** [lazyguyy/survivle#8]
I played today and guessed the word in five.
ZILCH
AXIOM
WAIVE
PAINT
RAINY

Then played some non daily games.
Then did some other stuff on my phone. Then returned to Survivle, and I'm seeing the first four guesses of my daily game and part of another game that I was more successful at.

ZILCH
AXIOM
WAIVE
PAINT
PUPPY
DOTTY
KISSY

**Comment by PaulCzege** [comment]
Now that I think about it, PUPPY, DOTTY, KISSY, were my first three guesses of a different game.

**Comment by lazyguyy** [comment]
Hmm, that is odd as the local word cache should only ever be written to when solving the daily puzzle. 
Do you remember whether Kissy was the solution to the other game?
Also; was the KISSY game played right after you finished the daily puzzle?

**Comment by PaulCzege** [comment]
I don't think it was. I think I got up to eight on one of the games I played, but not that one. PUPPY, DOTTY, KISSY were just the first three guesses of one game. Maybe the most recent one before I left Survivle, but I don't remember for sure.

**Comment by PaulCzege** [comment]
Y'know, PUPPY, DOTTY, KISSY could have been the first three guesses of a replay of the daily game.

**Comment by PaulCzege** [comment]
![Screenshot_20220311-091729](https://user-images.githubusercontent.com/101417937/157916363-d234f049-fde5-4390-b83f-4e76664b56ca.png)

**Comment by lazyguyy** [comment]
Huh, that is true. But it shouldn't let you replay the daily wordle either.
Although hmm... did you perhaps have the game open in two tabs, play in both of them simultanously without reloading the page? Because then both tabs are in "daily mode" and append their guesses to the local cache.

But what is also odd is that it didn't record you entering "RAINY"

**Comment by PaulCzege** [comment]
Hmm. I don't think I had it open in two tabs. But Chrome on Android does this thing where it launches a version of itself from links within other apps. It's possible I played Survivle within Chrome, and then went to it again from Chrome within Twitter after reading an article link from Twitter.

**Comment by lazyguyy** [comment]
I think that might be the problem. I have at least managed to recreate it by playing in two tabs simultanously.
Thanks for reporting and helping me figure this out; without your insight that these were two playthroughs of the same daily puzzle bungled together (at least I hope that was the problem) I would have probably been sitting here confused for a long time.

I will push a fix for that shortly.

**Comment by PaulCzege** [comment]
You're welcome. Thanks for creating the game. It's really fun.

**Comment by lazyguyy** [comment]
Fix should be live now; let me know if the problem reoccurs
